apiVersion: v1
kind: Pod
metadata:
  namespace: kn1
  name: securebeats
spec:
  containers:
    - name: heartbeats
      image: gcr.io/knative-nightly/knative.dev/eventing/cmd/heartbeats:latest
      env:
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      args:
      - --sink=http://broker-ingress.knative-eventing.svc.cluster.local/kn1/export
      - --eventType=dev.knative.eventing.securemessage
      - --label="I want to share this message with authenticated people"
      - --period=10s

---

apiVersion: v1
kind: Secret
metadata:
  namespace: kn1
  name: password1
type: Opaque
stringData:
  password: pw1

---

apiVersion: targets.triggermesh.io/v1alpha1
kind: CloudEventsTarget
metadata:
  namespace: kn1
  name: export-secure
spec:
  endpoint: https://cloudeventssource-gateway-auth-kn2.dev.triggermesh.io/mypath
  credentials:
    basicAuth:
      username: user1
      password:
        valueFromSecret:
          name: password1
          key: password

---

kind: Trigger
apiVersion: eventing.knative.dev/v1
metadata:
  namespace: kn1
  name: export-to-kn2-secure
spec:
  broker: export
  filter:
    attributes:
      type: dev.knative.eventing.securemessage
  subscriber:
    ref:
      apiVersion: targets.triggermesh.io/v1alpha1
      kind: CloudEventsTarget
      name: export-secure
