apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  namespace: kn1
  name: export

---

apiVersion: v1
kind: Pod
metadata:
  namespace: kn1
  name: plainbeats
spec:
  containers:
    - name: heartbeats
      image: gcr.io/knative-nightly/knative.dev/eventing/cmd/heartbeats:latest
      env:
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      args:
      - --sink=http://broker-ingress.knative-eventing.svc.cluster.local/kn1/export
      - --eventType=dev.knative.eventing.plainmessage
      - --label="I want to share this message to the world"
      - --period=10s

---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: kn1
  name: all-kn1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
      - image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display

---

kind: Trigger
apiVersion: eventing.knative.dev/v1
metadata:
  namespace: kn1
  name: all-kn1
spec:
  broker: export
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: all-kn1
